# Generated by Django 4.1 on 2022-08-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('IpfsAddress', models.CharField(max_length=100, unique=True)),
                ('NftType', models.CharField(choices=[('Picture', 'Picture'), ('Voice', 'Voice'), ('Gif', 'Gif')], max_length=100)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastPrice', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IRL', models.DecimalField(decimal_places=2, max_digits=6)),
                ('USD', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
